In [1]:
import numpy as np

# a.
# 1.
random_vector = np.random.randint(1, 21, size=15)
reshaped_array = random_vector.reshape(3, 5)

In [2]:
# 2.
print("Reshaped array shape:", reshaped_array.shape)

Reshaped array shape: (3, 5)


In [4]:
# 3.
reshaped_array[np.arange(reshaped_array.shape[0]), np.argmax(reshaped_array, axis=1)] = 0
print("Modified array with max replaced by 0 in each row:")
print(reshaped_array)

# Create a 2-dimensional array of size 4 * 3
two_dim_array = np.zeros((4, 3), dtype=np.int32)
print("\nShape of the 2D array:", two_dim_array.shape)
print("Type of elements in the 2D array:", type(two_dim_array[0, 0]))
print("Data type of the elements in the 2D array:", two_dim_array.dtype)

Modified array with max replaced by 0 in each row:
[[ 0  1  0  5  2]
 [14  0  0  2 12]
 [14 13 14  0  0]]

Shape of the 2D array: (4, 3)
Type of elements in the 2D array: <class 'numpy.int32'>
Data type of the elements in the 2D array: int32


In [5]:
# b.
square_array = np.array([[1, 3], [0, 2]])
eigenvalues, eigenvectors = np.linalg.eig(square_array)
print("\nEigenvalues:", eigenvalues)
print("Right eigenvectors:")
print(eigenvectors)


Eigenvalues: [1. 2.]
Right eigenvectors:
[[1.         0.9486833 ]
 [0.         0.31622777]]


In [6]:

# c.
given_array = np.array([[1, 2, 3], [0, 2, 0], [0, 0, 3.45]])
sum_of_diagonal = np.trace(given_array)
print("\nSum of diagonal elements:", sum_of_diagonal)



Sum of diagonal elements: 6.45


In [9]:
# d.
import numpy as np

array_to_reshape = np.array([1, 3, 4, 1]).reshape(2, 2)
print("Original 2x2 array:")
print(array_to_reshape)

# Reshape to 3x2
try:
    reshaped_3x2 = np.reshape(array_to_reshape, (3, 2))
    print("\nReshaped 3x2 array:")
    print(reshaped_3x2)
except ValueError as e:
    print("\nValueError occurred while reshaping to 3x2:", e)

# Reshape to 2x3
try:
    reshaped_2x3 = np.reshape(array_to_reshape, (2, 3))
    print("\nReshaped 2x3 array:")
    print(reshaped_2x3)
except ValueError as e:
    print("\nValueError occurred while reshaping to 2x3:", e)


Original 2x2 array:
[[1 3]
 [4 1]]

ValueError occurred while reshaping to 3x2: cannot reshape array of size 4 into shape (3,2)

ValueError occurred while reshaping to 2x3: cannot reshape array of size 4 into shape (2,3)
